version = 0.1
[default.deploy.parameters]
stack_name = "silkstream-api"
resolve_s3 = true
s3_prefix = "silkstream-api"
region = "eu-central-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
