AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SilkStream API

Globals:
  Function:
    Timeout: 180
    Runtime: nodejs18.x
    Environment:
      Variables:
        AWS_BUCKET_NAME: silkstream-vids

Resources:
  SilkStreamApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,PATCH,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'https://d36s6tbbzamzr1.cloudfront.net'"

  SSMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource:
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/silkstream/*"

  SilkStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../server/dist
      Handler: lambdaHandler.handler
      Events:
        GetVideos:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /videos
            Method: GET
        GetVideoById:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /videos/{videoId}
            Method: GET
        GetUploadUrl:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /get-upload-url
            Method: POST
        UpdateMetadata:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /videos/{videoId}/metadata
            Method: PATCH
        GetTagSuggestions:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /tags/suggest
            Method: GET
        GetTags:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /tags
            Method: GET
        GetCategories:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /categories
            Method: GET
        BatchUpsertMetadata:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /videos/batch-upsert
            Method: POST
        BatchDeleteVideos:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /videos/batch-delete
            Method: POST
        DeleteVideo:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /videos/{videoId}
            Method: DELETE
        ToggleFavorite:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /videos/{videoId}/favorite
            Method: POST
        GetRandomFavorites:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /videos/random-favorites
            Method: GET
        GetAllVideos:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /videos-archive
            Method: GET
        CheckFavorite:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /videos/{videoId}/is-favorite
            Method: GET
        GetUntaggedVideos:
          Type: Api
          Properties:
            RestApiId: !Ref SilkStreamApi
            Path: /videos-untagged
            Method: GET
      Policies:
        - S3CrudPolicy:
            BucketName: silkstream-vids
        - DynamoDBCrudPolicy:
            TableName: silkstream-vids
        - DynamoDBCrudPolicy:
            TableName: silkstream-tags
        - DynamoDBCrudPolicy:
            TableName: silkstream-favorites
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
                - ssm:GetParametersByPath
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/silkstream/*"

  SilkStreamFavoritesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: silkstream-favorites
      AttributeDefinitions:
        - AttributeName: videoId
          AttributeType: S
      KeySchema:
        - AttributeName: videoId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
